/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateFaqRequest {
  'question' : string,
  'answer' : string,
  'category' : string,
}
export interface CreateTicketRequest { 'subject' : string, 'message' : string }
export interface CryptoAssetPublic {
  'name' : string,
  'priceChangePercent' : number,
  'price' : number,
  'symbol' : CryptoSymbol,
}
export type CryptoSymbol = string;
export interface DepositResult {
  'depositAmount' : number,
  'newBalance' : number,
  'bonusEarned' : number,
}
export interface FaqEntryPublic {
  'id' : bigint,
  'question' : string,
  'createdAt' : Timestamp,
  'answer' : string,
  'category' : string,
}
export interface HoldingPublic {
  'currentPrice' : number,
  'currentValue' : number,
  'quantity' : number,
  'symbol' : CryptoSymbol,
}
export interface PlaceOrderRequest {
  'tradeType' : TradeType,
  'quantity' : number,
  'symbol' : CryptoSymbol,
}
export type PlaceOrderResult = { 'ok' : TradeOrder } |
  { 'err' : string };
export interface RegisterRequest {
  'username' : string,
  'passwordHash' : string,
}
export interface ReplyTicketRequest { 'ticketId' : bigint, 'message' : string }
export type Role = { 'admin' : null } |
  { 'customer' : null };
export interface SendCryptoRequest {
  'toAddress' : string,
  'amount' : number,
  'symbol' : CryptoSymbol,
}
export type SendCryptoResult = { 'ok' : Transfer } |
  { 'err' : string };
export interface TicketPublic {
  'id' : bigint,
  'status' : TicketStatus,
  'subject' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'message' : string,
  'replies' : Array<TicketReply>,
}
export interface TicketReply {
  'authorId' : UserId,
  'message' : string,
  'timestamp' : Timestamp,
  'isAdmin' : boolean,
}
export type TicketStatus = { 'closed' : null } |
  { 'in_progress' : null } |
  { 'open' : null };
export type Timestamp = bigint;
export interface TradeOrder {
  'id' : bigint,
  'total' : number,
  'tradeType' : TradeType,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'quantity' : number,
  'price' : number,
  'symbol' : CryptoSymbol,
}
export type TradeType = { 'buy' : null } |
  { 'sell' : null };
export interface Transaction {
  'id' : bigint,
  'userId' : UserId,
  'description' : string,
  'timestamp' : Timestamp,
  'txType' : TxType,
  'amount' : number,
}
export interface Transfer {
  'id' : bigint,
  'status' : TransferStatus,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'toAddress' : string,
  'amount' : number,
  'symbol' : CryptoSymbol,
}
export type TransferStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type TxType = { 'trade' : null } |
  { 'deposit' : null } |
  { 'bonus' : null } |
  { 'transfer' : null };
export interface UpdateFaqRequest {
  'id' : bigint,
  'question' : string,
  'answer' : string,
  'category' : string,
}
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'status' : UserStatus,
  'username' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'usdBalance' : number,
}
export type UserStatus = { 'active' : null } |
  { 'suspended' : null };
export interface _SERVICE {
  'adminAdjustUserBalance' : ActorMethod<
    [UserId, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllOrders' : ActorMethod<[], Array<TradeOrder>>,
  'adminGetAllTickets' : ActorMethod<[], Array<TicketPublic>>,
  'adminGetAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'adminGetAllUsers' : ActorMethod<[], Array<UserPublic>>,
  'adminSuspendUser' : ActorMethod<
    [UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUnsuspendUser' : ActorMethod<
    [UserId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateTicketStatus' : ActorMethod<
    [bigint, TicketStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createFaq' : ActorMethod<
    [CreateFaqRequest],
    { 'ok' : FaqEntryPublic } |
      { 'err' : string }
  >,
  'createTicket' : ActorMethod<[CreateTicketRequest], TicketPublic>,
  'deleteFaq' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deposit' : ActorMethod<
    [number],
    { 'ok' : DepositResult } |
      { 'err' : string }
  >,
  'getAllAssets' : ActorMethod<[], Array<CryptoAssetPublic>>,
  'getAllFaq' : ActorMethod<[], Array<FaqEntryPublic>>,
  'getMyHoldings' : ActorMethod<[], Array<HoldingPublic>>,
  'getMyOrders' : ActorMethod<[], Array<TradeOrder>>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getMyTickets' : ActorMethod<[], Array<TicketPublic>>,
  'getMyTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getMyTransfers' : ActorMethod<[], Array<Transfer>>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], PlaceOrderResult>,
  'register' : ActorMethod<
    [RegisterRequest],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'replyToTicket' : ActorMethod<
    [ReplyTicketRequest],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendCrypto' : ActorMethod<[SendCryptoRequest], SendCryptoResult>,
  'updateFaq' : ActorMethod<
    [UpdateFaqRequest],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];