/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const Timestamp = IDL.Int;
export const CryptoSymbol = IDL.Text;
export const TradeOrder = IDL.Record({
  'id' : IDL.Nat,
  'total' : IDL.Float64,
  'tradeType' : TradeType,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : CryptoSymbol,
});
export const TicketStatus = IDL.Variant({
  'closed' : IDL.Null,
  'in_progress' : IDL.Null,
  'open' : IDL.Null,
});
export const TicketReply = IDL.Record({
  'authorId' : UserId,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'isAdmin' : IDL.Bool,
});
export const TicketPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'subject' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'replies' : IDL.Vec(TicketReply),
});
export const TxType = IDL.Variant({
  'trade' : IDL.Null,
  'deposit' : IDL.Null,
  'bonus' : IDL.Null,
  'transfer' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'txType' : TxType,
  'amount' : IDL.Float64,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'customer' : IDL.Null });
export const UserPublic = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'usdBalance' : IDL.Float64,
});
export const CreateFaqRequest = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const FaqEntryPublic = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'createdAt' : Timestamp,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});
export const CreateTicketRequest = IDL.Record({
  'subject' : IDL.Text,
  'message' : IDL.Text,
});
export const DepositResult = IDL.Record({
  'depositAmount' : IDL.Float64,
  'newBalance' : IDL.Float64,
  'bonusEarned' : IDL.Float64,
});
export const CryptoAssetPublic = IDL.Record({
  'name' : IDL.Text,
  'priceChangePercent' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : CryptoSymbol,
});
export const HoldingPublic = IDL.Record({
  'currentPrice' : IDL.Float64,
  'currentValue' : IDL.Float64,
  'quantity' : IDL.Float64,
  'symbol' : CryptoSymbol,
});
export const TransferStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Transfer = IDL.Record({
  'id' : IDL.Nat,
  'status' : TransferStatus,
  'userId' : UserId,
  'timestamp' : Timestamp,
  'toAddress' : IDL.Text,
  'amount' : IDL.Float64,
  'symbol' : CryptoSymbol,
});
export const PlaceOrderRequest = IDL.Record({
  'tradeType' : TradeType,
  'quantity' : IDL.Float64,
  'symbol' : CryptoSymbol,
});
export const PlaceOrderResult = IDL.Variant({
  'ok' : TradeOrder,
  'err' : IDL.Text,
});
export const RegisterRequest = IDL.Record({
  'username' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const ReplyTicketRequest = IDL.Record({
  'ticketId' : IDL.Nat,
  'message' : IDL.Text,
});
export const SendCryptoRequest = IDL.Record({
  'toAddress' : IDL.Text,
  'amount' : IDL.Float64,
  'symbol' : CryptoSymbol,
});
export const SendCryptoResult = IDL.Variant({
  'ok' : Transfer,
  'err' : IDL.Text,
});
export const UpdateFaqRequest = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminAdjustUserBalance' : IDL.Func(
      [UserId, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
  'adminGetAllTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
  'adminGetAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'adminSuspendUser' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUnsuspendUser' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateTicketStatus' : IDL.Func(
      [IDL.Nat, TicketStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createFaq' : IDL.Func(
      [CreateFaqRequest],
      [IDL.Variant({ 'ok' : FaqEntryPublic, 'err' : IDL.Text })],
      [],
    ),
  'createTicket' : IDL.Func([CreateTicketRequest], [TicketPublic], []),
  'deleteFaq' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deposit' : IDL.Func(
      [IDL.Float64],
      [IDL.Variant({ 'ok' : DepositResult, 'err' : IDL.Text })],
      [],
    ),
  'getAllAssets' : IDL.Func([], [IDL.Vec(CryptoAssetPublic)], ['query']),
  'getAllFaq' : IDL.Func([], [IDL.Vec(FaqEntryPublic)], ['query']),
  'getMyHoldings' : IDL.Func([], [IDL.Vec(HoldingPublic)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getMyTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
  'getMyTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyTransfers' : IDL.Func([], [IDL.Vec(Transfer)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [PlaceOrderResult], []),
  'register' : IDL.Func(
      [RegisterRequest],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'replyToTicket' : IDL.Func(
      [ReplyTicketRequest],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendCrypto' : IDL.Func([SendCryptoRequest], [SendCryptoResult], []),
  'updateFaq' : IDL.Func(
      [UpdateFaqRequest],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const TradeType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const Timestamp = IDL.Int;
  const CryptoSymbol = IDL.Text;
  const TradeOrder = IDL.Record({
    'id' : IDL.Nat,
    'total' : IDL.Float64,
    'tradeType' : TradeType,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : CryptoSymbol,
  });
  const TicketStatus = IDL.Variant({
    'closed' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  });
  const TicketReply = IDL.Record({
    'authorId' : UserId,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'isAdmin' : IDL.Bool,
  });
  const TicketPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'replies' : IDL.Vec(TicketReply),
  });
  const TxType = IDL.Variant({
    'trade' : IDL.Null,
    'deposit' : IDL.Null,
    'bonus' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'txType' : TxType,
    'amount' : IDL.Float64,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'customer' : IDL.Null });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'usdBalance' : IDL.Float64,
  });
  const CreateFaqRequest = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const FaqEntryPublic = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'createdAt' : Timestamp,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  const CreateTicketRequest = IDL.Record({
    'subject' : IDL.Text,
    'message' : IDL.Text,
  });
  const DepositResult = IDL.Record({
    'depositAmount' : IDL.Float64,
    'newBalance' : IDL.Float64,
    'bonusEarned' : IDL.Float64,
  });
  const CryptoAssetPublic = IDL.Record({
    'name' : IDL.Text,
    'priceChangePercent' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : CryptoSymbol,
  });
  const HoldingPublic = IDL.Record({
    'currentPrice' : IDL.Float64,
    'currentValue' : IDL.Float64,
    'quantity' : IDL.Float64,
    'symbol' : CryptoSymbol,
  });
  const TransferStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Transfer = IDL.Record({
    'id' : IDL.Nat,
    'status' : TransferStatus,
    'userId' : UserId,
    'timestamp' : Timestamp,
    'toAddress' : IDL.Text,
    'amount' : IDL.Float64,
    'symbol' : CryptoSymbol,
  });
  const PlaceOrderRequest = IDL.Record({
    'tradeType' : TradeType,
    'quantity' : IDL.Float64,
    'symbol' : CryptoSymbol,
  });
  const PlaceOrderResult = IDL.Variant({ 'ok' : TradeOrder, 'err' : IDL.Text });
  const RegisterRequest = IDL.Record({
    'username' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const ReplyTicketRequest = IDL.Record({
    'ticketId' : IDL.Nat,
    'message' : IDL.Text,
  });
  const SendCryptoRequest = IDL.Record({
    'toAddress' : IDL.Text,
    'amount' : IDL.Float64,
    'symbol' : CryptoSymbol,
  });
  const SendCryptoResult = IDL.Variant({ 'ok' : Transfer, 'err' : IDL.Text });
  const UpdateFaqRequest = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'adminAdjustUserBalance' : IDL.Func(
        [UserId, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
    'adminGetAllTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
    'adminGetAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'adminSuspendUser' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUnsuspendUser' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateTicketStatus' : IDL.Func(
        [IDL.Nat, TicketStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createFaq' : IDL.Func(
        [CreateFaqRequest],
        [IDL.Variant({ 'ok' : FaqEntryPublic, 'err' : IDL.Text })],
        [],
      ),
    'createTicket' : IDL.Func([CreateTicketRequest], [TicketPublic], []),
    'deleteFaq' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deposit' : IDL.Func(
        [IDL.Float64],
        [IDL.Variant({ 'ok' : DepositResult, 'err' : IDL.Text })],
        [],
      ),
    'getAllAssets' : IDL.Func([], [IDL.Vec(CryptoAssetPublic)], ['query']),
    'getAllFaq' : IDL.Func([], [IDL.Vec(FaqEntryPublic)], ['query']),
    'getMyHoldings' : IDL.Func([], [IDL.Vec(HoldingPublic)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(TradeOrder)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getMyTickets' : IDL.Func([], [IDL.Vec(TicketPublic)], ['query']),
    'getMyTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getMyTransfers' : IDL.Func([], [IDL.Vec(Transfer)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [PlaceOrderResult], []),
    'register' : IDL.Func(
        [RegisterRequest],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'replyToTicket' : IDL.Func(
        [ReplyTicketRequest],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendCrypto' : IDL.Func([SendCryptoRequest], [SendCryptoResult], []),
    'updateFaq' : IDL.Func(
        [UpdateFaqRequest],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };