/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TicketPublic {
    id: bigint;
    status: TicketStatus;
    subject: string;
    userId: UserId;
    createdAt: Timestamp;
    message: string;
    replies: Array<TicketReply>;
}
export interface PlaceOrderRequest {
    tradeType: TradeType;
    quantity: number;
    symbol: CryptoSymbol;
}
export type Timestamp = bigint;
export interface UserPublic {
    id: UserId;
    status: UserStatus;
    username: string;
    createdAt: Timestamp;
    role: Role;
    usdBalance: number;
}
export interface FaqEntryPublic {
    id: bigint;
    question: string;
    createdAt: Timestamp;
    answer: string;
    category: string;
}
export interface UpdateFaqRequest {
    id: bigint;
    question: string;
    answer: string;
    category: string;
}
export interface DepositResult {
    depositAmount: number;
    newBalance: number;
    bonusEarned: number;
}
export interface Transaction {
    id: bigint;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    txType: TxType;
    amount: number;
}
export interface Transfer {
    id: bigint;
    status: TransferStatus;
    userId: UserId;
    timestamp: Timestamp;
    toAddress: string;
    amount: number;
    symbol: CryptoSymbol;
}
export interface CryptoAssetPublic {
    name: string;
    priceChangePercent: number;
    price: number;
    symbol: CryptoSymbol;
}
export interface TradeOrder {
    id: bigint;
    total: number;
    tradeType: TradeType;
    userId: UserId;
    timestamp: Timestamp;
    quantity: number;
    price: number;
    symbol: CryptoSymbol;
}
export interface RegisterRequest {
    username: string;
    passwordHash: string;
}
export interface ReplyTicketRequest {
    ticketId: bigint;
    message: string;
}
export type PlaceOrderResult = {
    __kind__: "ok";
    ok: TradeOrder;
} | {
    __kind__: "err";
    err: string;
};
export interface TicketReply {
    authorId: UserId;
    message: string;
    timestamp: Timestamp;
    isAdmin: boolean;
}
export interface CreateFaqRequest {
    question: string;
    answer: string;
    category: string;
}
export interface HoldingPublic {
    currentPrice: number;
    currentValue: number;
    quantity: number;
    symbol: CryptoSymbol;
}
export type UserId = Principal;
export interface SendCryptoRequest {
    toAddress: string;
    amount: number;
    symbol: CryptoSymbol;
}
export type CryptoSymbol = string;
export interface CreateTicketRequest {
    subject: string;
    message: string;
}
export type SendCryptoResult = {
    __kind__: "ok";
    ok: Transfer;
} | {
    __kind__: "err";
    err: string;
};
export enum Role {
    admin = "admin",
    customer = "customer"
}
export enum TicketStatus {
    closed = "closed",
    in_progress = "in_progress",
    open = "open"
}
export enum TradeType {
    buy = "buy",
    sell = "sell"
}
export enum TransferStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TxType {
    trade = "trade",
    deposit = "deposit",
    bonus = "bonus",
    transfer = "transfer"
}
export enum UserStatus {
    active = "active",
    suspended = "suspended"
}
export interface backendInterface {
    adminAdjustUserBalance(targetId: UserId, newBalance: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllOrders(): Promise<Array<TradeOrder>>;
    adminGetAllTickets(): Promise<Array<TicketPublic>>;
    adminGetAllTransactions(): Promise<Array<Transaction>>;
    adminGetAllUsers(): Promise<Array<UserPublic>>;
    adminSuspendUser(targetId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUnsuspendUser(targetId: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateTicketStatus(ticketId: bigint, status: TicketStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createFaq(req: CreateFaqRequest): Promise<{
        __kind__: "ok";
        ok: FaqEntryPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createTicket(req: CreateTicketRequest): Promise<TicketPublic>;
    deleteFaq(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deposit(amount: number): Promise<{
        __kind__: "ok";
        ok: DepositResult;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllAssets(): Promise<Array<CryptoAssetPublic>>;
    getAllFaq(): Promise<Array<FaqEntryPublic>>;
    getMyHoldings(): Promise<Array<HoldingPublic>>;
    getMyOrders(): Promise<Array<TradeOrder>>;
    getMyProfile(): Promise<UserPublic | null>;
    getMyTickets(): Promise<Array<TicketPublic>>;
    getMyTransactionHistory(): Promise<Array<Transaction>>;
    getMyTransfers(): Promise<Array<Transfer>>;
    placeOrder(req: PlaceOrderRequest): Promise<PlaceOrderResult>;
    register(req: RegisterRequest): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    replyToTicket(req: ReplyTicketRequest): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendCrypto(req: SendCryptoRequest): Promise<SendCryptoResult>;
    updateFaq(req: UpdateFaqRequest): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CryptoSymbol as _CryptoSymbol, DepositResult as _DepositResult, FaqEntryPublic as _FaqEntryPublic, PlaceOrderRequest as _PlaceOrderRequest, PlaceOrderResult as _PlaceOrderResult, Role as _Role, SendCryptoResult as _SendCryptoResult, TicketPublic as _TicketPublic, TicketReply as _TicketReply, TicketStatus as _TicketStatus, Timestamp as _Timestamp, TradeOrder as _TradeOrder, TradeType as _TradeType, Transaction as _Transaction, Transfer as _Transfer, TransferStatus as _TransferStatus, TxType as _TxType, UserId as _UserId, UserPublic as _UserPublic, UserStatus as _UserStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminAdjustUserBalance(arg0: UserId, arg1: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAdjustUserBalance(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAdjustUserBalance(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllOrders(): Promise<Array<TradeOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllOrders();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllOrders();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllTickets(): Promise<Array<TicketPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTickets();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTickets();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactions();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactions();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSuspendUser(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSuspendUser(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSuspendUser(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUnsuspendUser(arg0: UserId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnsuspendUser(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnsuspendUser(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateTicketStatus(arg0: bigint, arg1: TicketStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateTicketStatus(arg0, to_candid_TicketStatus_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateTicketStatus(arg0, to_candid_TicketStatus_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFaq(arg0: CreateFaqRequest): Promise<{
        __kind__: "ok";
        ok: FaqEntryPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createFaq(arg0);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFaq(arg0);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTicket(arg0: CreateTicketRequest): Promise<TicketPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createTicket(arg0);
                return from_candid_TicketPublic_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTicket(arg0);
            return from_candid_TicketPublic_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFaq(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFaq(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFaq(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deposit(arg0: number): Promise<{
        __kind__: "ok";
        ok: DepositResult;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAssets(): Promise<Array<CryptoAssetPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return result;
        }
    }
    async getAllFaq(): Promise<Array<FaqEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFaq();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFaq();
            return result;
        }
    }
    async getMyHoldings(): Promise<Array<HoldingPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHoldings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHoldings();
            return result;
        }
    }
    async getMyOrders(): Promise<Array<TradeOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTickets(): Promise<Array<TicketPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTickets();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTickets();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactionHistory();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactionHistory();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransfers(): Promise<Array<Transfer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransfers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransfers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<PlaceOrderResult> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PlaceOrderResult_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PlaceOrderResult_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: RegisterRequest): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_variant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async replyToTicket(arg0: ReplyTicketRequest): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToTicket(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToTicket(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendCrypto(arg0: SendCryptoRequest): Promise<SendCryptoResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCrypto(arg0);
                return from_candid_SendCryptoResult_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCrypto(arg0);
            return from_candid_SendCryptoResult_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFaq(arg0: UpdateFaqRequest): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFaq(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFaq(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PlaceOrderResult_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaceOrderResult): PlaceOrderResult {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SendCryptoResult_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SendCryptoResult): SendCryptoResult {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_TicketPublic_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketPublic): TicketPublic {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TradeOrder_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeOrder): TradeOrder {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TransferStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferStatus): TransferStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Transfer_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transfer): Transfer {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    description: string;
    timestamp: _Timestamp;
    txType: _TxType;
    amount: number;
}): {
    id: bigint;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
    txType: TxType;
    amount: number;
} {
    return {
        id: value.id,
        userId: value.userId,
        description: value.description,
        timestamp: value.timestamp,
        txType: from_candid_TxType_n15(_uploadFile, _downloadFile, value.txType),
        amount: value.amount
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    username: string;
    createdAt: _Timestamp;
    role: _Role;
    usdBalance: number;
}): {
    id: UserId;
    status: UserStatus;
    username: string;
    createdAt: Timestamp;
    role: Role;
    usdBalance: number;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n20(_uploadFile, _downloadFile, value.status),
        username: value.username,
        createdAt: value.createdAt,
        role: from_candid_Role_n22(_uploadFile, _downloadFile, value.role),
        usdBalance: value.usdBalance
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TransferStatus;
    userId: _UserId;
    timestamp: _Timestamp;
    toAddress: string;
    amount: number;
    symbol: _CryptoSymbol;
}): {
    id: bigint;
    status: TransferStatus;
    userId: UserId;
    timestamp: Timestamp;
    toAddress: string;
    amount: number;
    symbol: CryptoSymbol;
} {
    return {
        id: value.id,
        status: from_candid_TransferStatus_n32(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        toAddress: value.toAddress,
        amount: value.amount,
        symbol: value.symbol
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    total: number;
    tradeType: _TradeType;
    userId: _UserId;
    timestamp: _Timestamp;
    quantity: number;
    price: number;
    symbol: _CryptoSymbol;
}): {
    id: bigint;
    total: number;
    tradeType: TradeType;
    userId: UserId;
    timestamp: Timestamp;
    quantity: number;
    price: number;
    symbol: CryptoSymbol;
} {
    return {
        id: value.id,
        total: value.total,
        tradeType: from_candid_TradeType_n5(_uploadFile, _downloadFile, value.tradeType),
        userId: value.userId,
        timestamp: value.timestamp,
        quantity: value.quantity,
        price: value.price,
        symbol: value.symbol
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TicketStatus;
    subject: string;
    userId: _UserId;
    createdAt: _Timestamp;
    message: string;
    replies: Array<_TicketReply>;
}): {
    id: bigint;
    status: TicketStatus;
    subject: string;
    userId: UserId;
    createdAt: Timestamp;
    message: string;
    replies: Array<TicketReply>;
} {
    return {
        id: value.id,
        status: from_candid_TicketStatus_n10(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        userId: value.userId,
        createdAt: value.createdAt,
        message: value.message,
        replies: value.replies
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    in_progress: null;
} | {
    open: null;
}): TicketStatus {
    return "closed" in value ? TicketStatus.closed : "in_progress" in value ? TicketStatus.in_progress : "open" in value ? TicketStatus.open : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trade: null;
} | {
    deposit: null;
} | {
    bonus: null;
} | {
    transfer: null;
}): TxType {
    return "trade" in value ? TxType.trade : "deposit" in value ? TxType.deposit : "bonus" in value ? TxType.bonus : "transfer" in value ? TxType.transfer : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "suspended" in value ? UserStatus.suspended : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
}): Role {
    return "admin" in value ? Role.admin : "customer" in value ? Role.customer : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FaqEntryPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FaqEntryPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DepositResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: DepositResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransferStatus {
    return "pending" in value ? TransferStatus.pending : "completed" in value ? TransferStatus.completed : "failed" in value ? TransferStatus.failed : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TradeOrder;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TradeOrder;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TradeOrder_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserPublic_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Transfer;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Transfer;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Transfer_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeType {
    return "buy" in value ? TradeType.buy : "sell" in value ? TradeType.sell : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeOrder>): Array<TradeOrder> {
    return value.map((x)=>from_candid_TradeOrder_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transfer>): Array<Transfer> {
    return value.map((x)=>from_candid_Transfer_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TicketPublic>): Array<TicketPublic> {
    return value.map((x)=>from_candid_TicketPublic_n8(_uploadFile, _downloadFile, x));
}
function to_candid_PlaceOrderRequest_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderRequest): _PlaceOrderRequest {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_TicketStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): _TicketStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tradeType: TradeType;
    quantity: number;
    symbol: CryptoSymbol;
}): {
    tradeType: _TradeType;
    quantity: number;
    symbol: _CryptoSymbol;
} {
    return {
        tradeType: to_candid_TradeType_n36(_uploadFile, _downloadFile, value.tradeType),
        quantity: value.quantity,
        symbol: value.symbol
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketStatus): {
    closed: null;
} | {
    in_progress: null;
} | {
    open: null;
} {
    return value == TicketStatus.closed ? {
        closed: null
    } : value == TicketStatus.in_progress ? {
        in_progress: null
    } : value == TicketStatus.open ? {
        open: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeType.buy ? {
        buy: null
    } : value == TradeType.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
